
#######################
# General Configuration
#######################
language: java
sudo: false
jdk:
  - openjdk8
os:
  - linux
dist: trusty

install:
  - mvn -U -e -C -B -P doUpdateSite dependency:go-offline

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "preesm-sonarcloud-org"
    token:
      secure: "7edfa331c5de80bf665aee04f0e9dbcbc3efa122"
    branches: .*

script: ./releng/build_and_test.sh --fast

